const createId = () => crypto.randomUUID();

const item = (name, quantity = 1) => ({
  id: createId(),
  name,
  checked: true,
  quantity,
});

const list = (name, items) => ({
  id: createId(),
  name,
  items,
});

export const createInitialState = () => ({
  lists: [
    list('MERCHEKAO', [
      item('Champú pelo'),
      item('Panes congelados'),
      item('Poquitos'),
      item('Lomo'),
      item('Cereales Avena'),
      item('Pasta de dientes'),
      item('Desodorante de roll-on'),
      item('Galletas avena 0%'),
      item('Plátanos'),
      item('Peras'),
      item('Uvas'),
      item('Canela'),
      item('Ajo en polvo'),
      item('Chocolate negro tableta 85%'),
      item('Arroz'),
      item('Lasaña'),
      item('Cápsula café naranja'),
      item('Panela'),
      item('Embutido: Jamón 92%'),
      item('Queso blanco en triángulos'),
      item('Pan de molde'),
      item('Queso batido'),
      item('Leche Semi sin lactosa'),
      item('Queso rallado'),
      item('Bebida isotónica'),
      item('Garrafa agua 8L'),
      item('Cacahuetes'),
      item('Nueces cáscara'),
      item('Cornflakes', 2),
      item('Avena', 2),
      item('Frutos rojos congelados'),
      item('Espaguetis'),
      item('Harina avena'),
      item('Cebolla /Pimiento /brócoli congelado'),
      item('Mix verduras congeladas'),
      item('Pipas sal', 2),
      item('Huevos'),
      item('Papas'),
      item('Yogurt natural'),
      item('Cepillos blandos'),
      item('Tortitas fajita integral'),
      item('Pollo congelado'),
      item('Atún peque/grande', 2),
      item('Caballa', 2),
      item('Salmon congelado'),
      item('COLACAO Hacendado 0%'),
      item('Tarta queso mami'),
      item('Helado 0%'),
      item('Servilletas'),
      item('Tortitas Trigo'),
      item('Café en polvo'),
      item('Toallitas húmedas WC'),
      item('Cepillos dientes'),
      item('Papas fritas'),
      item('Champú cuerpo'),
      item('Frutos secos mix'),
      item('Cafe grano'),
      item('Bolsas congelar pequeñas zip'),
      item('Ajo, cebolla, pim. Dulce y curry en polvo'),
      item('Aceite Oliva'),
    ]),
    list('ANODESIN', [
      item('PIENSO BROWNIE'),
      item('PATÉ BROWNIE'),
      item('ARENA BROWNIE'),
      item('Lentillas'),
      item('Proteína'),
      item('Creatina'),
      item('Peluquería'),
    ]),
  ],
});
